### ISSUE TITLE
Should we move donator/admin/dev/etc heads from fossils to fishing instead? / Redoing fossil rewards

### ISSUE THREAD

**Issue by RedDevel2** [CivMC/CivDocker#237]
Fossil rewards currently are quite underwhelming, I think they can be revisited to be more exciting when cracked.

Now that fishing has been successfully implemented. we can move all the decorative heads that would otherwise fill up the chest when cracking fossils to the fishing loot table with it's own "player" rarity. (and actually give them name and lore about the players)
Freeing up the fossils to be reworked, and also to make adding new donator heads less cumbersome with needing to be part of a whole update.

**Comment by awoo-civ** [comment]
> Fossil rewards currently are quite underwhelming, I think they can be revisited to be more exciting when cracked.

Very much so. For example all the iron tools. Completely pointless. 

The mob eggs are nice though.

**Comment by Solitaire7** [comment]
Agree, the current fossil rewards are very underwhelming and a lot of them are irrelevant when compared to how rare they are. The quantities of iron blocks, diamonds, noteblocks, jukeboxes, E blocks etc... you get are incredibly trivial/underwhelming considering the amount of mining you have to do to get enough fossils to realistically get rewards of those rareties. Similarly, the very rare enchanted tools are of little worth when you consider how much mining you have to do to get enough fossils to get a drop from that rarety scale. 

If it's possible I think it'd be cool to have some of the rarest rewards be enchanted diamond/netherite tools that have levels 1 or 2 tiers beyond what is possible through conventional enchanting, such as fortune 4 or 5, efficiency 7 or 8 (maybe high enough efficiency such that with haste 2 deepslate is insta break) etc.... If tools were then made to be repairable infinitely but at exponentially increasing costs it'd mean that these tools would likely be rare enough such that only a few exist at any one time and since they're so rare as to not be getting replaced by a new one you'll continue to repair them even when the costs are very high.

Another potential very rare reward (maybe even the rarest) could be a small amount (8-16 blocks) of "reinforced deepslate". Reinforced deepslate is a block with slightly higher hardness than obsidian (5 hardness higher) and once you've placed it it can never be picked back up (if the block is broken it doesn't drop)

**Comment by voroxity** [comment]
Agreed. A potential solution would be to both re-work the loot table and or add a unique reward that can only be obtained from fossil and is required for some crafting. Players essens with a moderate to low chance could be a potential addition that would make cracking relevant.
