### ISSUE TITLE
Mysqld bottlenecking server with max db connections

### ISSUE THREAD

**Issue by wingzero54** [CivMC/CivDocker#39]
We reach the maximum number of mysqld connections allowed and get severely bottlenecked, CPU usage pegs at 90%+ and server loses 5-10 TPS immediately and becomes laggy. 

All the civ plugins seem to create numerous db connections and surely are not maximizing their usage. CivSpy is connected to PostgreSQL so I don't believe it has any relation to this mysqldb connection issue.

**Comment by wingzero54** [comment]
I am merging https://github.com/CivMC/CivModCore/pull/73 to see if we can pinpoint if a specific plugin's database calls may be causing the issue

**Comment by wingzero54** [comment]
CMC Stat is consistently showing numbers like this so I am not sure if max connections is the issue. I have been unable to pinpoint the lag that occurs alongside high cpu usage of server & mysqld, next step may be to use the slow query log for sql to determine if any queries are hanging or anything like that. 

[22:37:56 INFO]: Chunk loading statistics:
[22:37:56 INFO]: World Count: 2
[22:37:56 INFO]: Thread Count: 4
[22:37:56 INFO]: [Citadel]
[22:37:56 INFO]: Load count: 2422578
[22:37:56 INFO]: Total load time: 640931.44 ms
[22:37:56 INFO]: Min load time: 0.08 ms
[22:37:56 INFO]: Max load time: 185.96 ms
[22:37:56 INFO]: Avg load time: 0.26 ms
[22:37:56 INFO]: [RealisticBiomes]
[22:37:56 INFO]: Load count: 2422578
[22:37:56 INFO]: Total load time: 527483.72 ms
[22:37:56 INFO]: Min load time: 0.08 ms
[22:37:56 INFO]: Max load time: 188.06 ms
[22:37:56 INFO]: Avg load time: 0.21 ms

**Comment by Aleksey-Terzi** [comment]
The statistic shows that we don't have a problem with ChunkMeta loading atm.
I think the problem "crash because of no connections" is partially solved after the connection pool size was increased.
Though I still think we still have a high load on MySql because of ActivityMap select/insert.
For example, if my character has 5 groups where he is MODS then every time I load, every time I visit another 8 chunk regions it will so insert/update 605 records.
Also, the current cache size is not enough to keep all groups so it constantly loads.
From what I understand we have 13M records and 200K cache size.

The structure of the cache needs to be changed to keep chunks rather than groups (like ChunkMeta does)

**Comment by Aleksey-Terzi** [comment]
I think this issue is fixed by these PRs:
1. https://github.com/CivMC/Citadel/pull/39
2. https://github.com/CivMC/JukeAlert/pull/19
