### ISSUE TITLE
Reduce memory usage of plugins

### ISSUE THREAD

**Issue by Maxopoly** [CivMC/CivDocker#5]
> Banstick/Citadel/JukeAlert memory usage leads to higher than average young gen gc which doesn't help, and at high player counts very heavy old gen GC that causes lag spikes

I think past fixing the chunk meta issues, which we already did, there's not terribly much we can do about RAM. Using ZGC (now that we're on Java 17), would likely bring severe improvements in regards to garbage collection though. See https://github.com/CivMC/CivDocker/issues/6

**Comment by wingzero54** [comment]
JukeAlert memory usage is no longer an issue since snitch logs were removed from memory, and citadel memory usage should be better with the chunk meta being cleared more reliably. I think we'll find a big garbage collection difference with the chunk meta changes. 

Based on benchmarks and reviews, I believe G1 is still better suited for our needs than ZGC. https://ionutbalosin.com/2019/12/jvm-garbage-collectors-benchmarks-report-19-12/ this benchmark finds that ZGC is best when you can reclaim a majority of the heap, while G1 is better when a majority of the heap is constantly being occupied, which was our experience on CivClassic. 

I would like to start the server using G1 as a baseline and switch to ZGC if we continue to have issues.

**Comment by Protonull** [comment]
> this benchmark finds that ZGC is best when you can reclaim a majority of the heap, while G1 is better when a majority of the heap is constantly being occupied

Might be worth switching Bungee / Velocity over to ZGC. Bungee had to be given progressively more RAM to handle more and more connections. This'll likely be less of an issue since you don't intend to use ViaBackwards, but either way it seems like the perfect use case.

**Comment by Maxopoly** [comment]
> Bungee had to be given progressively more RAM to handle more and more connections.

Which is something requiring further investigation as well, as we were off by a factor of 100 or more from the recommended amount of RAM per player

**Comment by wingzero54** [comment]
The improved tracking we have should give us better visibility on that, it's hard to analyze an issue with only small snapshots from spark.
